GET http://localhost:5000/notes

###
POST http://localhost:5000/add-notes
Content-Type: application/json

{
    "title": "Diary",
    "content": "Coba aja dulu"
}

###
PUT http://localhost:5000/update-notes/2
Content-Type: application/json

{
    "title": "Apalah",
    "content": "kemarin aku ke magelang"
}

###
DELETE http://localhost:5000/delete-notes/3